#!/usr/bin/sh

## colorful man pages
#man() {
#    env \
#        LESS_TERMCAP_mb=$(printf "\e[1;37m") \
#        LESS_TERMCAP_md=$(printf "\e[1;34m") \
#        LESS_TERMCAP_me=$(printf "\e[0m") \
#        LESS_TERMCAP_se=$(printf "\e[0m") \
#        LESS_TERMCAP_so=$(printf "\e[1;35m") \
#        LESS_TERMCAP_ue=$(printf "\e[0m") \
#        LESS_TERMCAP_us=$(printf "\e[1;36m") \
#            man "$@"
#}

# colorful man pages
man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[01;31m") \
        LESS_TERMCAP_md=$(printf "\e[01;38;5;74m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[01;38;5;198m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[04;38;5;146m") \
            man "$@"
}

## # Less Colors for Man Pages
## export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
## export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
## export LESS_TERMCAP_me=$'\E[0m'           # end mode
## export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
## export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
## export LESS_TERMCAP_ue=$'\E[0m'           # end underline
## export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
